export {About} from './About/About'
export {Footer} from './Footer/Footer'
export {Header} from './Header/Header'
export {Skills} from './Skills/Skills'
export {Projects} from './Projects/Projects'
export {Contact} from './Contact/Contact'